### ISSUE TITLE
Ambiguity between folder and branch

### ISSUE THREAD

**Issue by TheRolfFR** [drud/action-cross-commit#12]
Hello,

I have been using your action and it is really cool!

I want to push on the doc branch but I have a folder with the same name.
So when doing the checkout, it gives this:
```
Cloning into '/tmp/tmp.BmCHno'...
Checking out doc from origin.
fatal: 'doc' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
```

Could I or you fix this?

By the way, is there a way I could push on the same repo but only a different branch? Not to adapt the ``destination-repository`` across multiple repos?

**Comment by wozniakjan** [comment]
Hi, thank you for the kind words :)
I'm sure we can sort both of these, but unfortunately, we will have to likely make a living fork because this is no longer maintained due to https://twitter.com/cyberswat/status/1382373295329136642?lang=en.
